<?php
/**
 * @file
 */

/**
 * Implements hook_views_api().
 */
function views_list_sort_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'views_list_sort') . '/views',
  );
}

/**
 * Implements hook_autoload_info().
 */
function views_list_sort_autoload_info() {
  return array(
    'views_list_sort_handler_sort_allowed_values' => 'includes/views_list_sort_handler_sort_allowed_values.inc',
  );
}
