<?php

/**
 * Implements hook_views_api() from Views().
 */
function views_list_sort_views_api($module = NULL, $api = NULL) {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'views_list_sort') . '/views',
  );
}

/**
 * Implements hook_autoload_info().
 */
function views_list_sort_autoload_info() {
  return array(
    'views_list_sort_handler_sort_allowed_values' => 'views/handlers/views_list_sort_handler_sort_allowed_values.inc',
  );
}
